site_name: HackOps Lab
site_url: https://jwaler.github.io/HackOps/
site_description: "HackOps Golden Book"
site_author: "HackOps Team"

theme:
  name: material
  custom_dir: overrides
  copyright: ""
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/logo.ico
  logo: images/logo.png

markdown_extensions:
  - admonition            # base callouts
  - attr_list
  - def_list
  - footnotes
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - check
        - important
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - callouts
  - search
  - tags
  - git-revision-date
#  - git-committers
  - rss:
      match_path: ".*"
      date_from_meta:
        as_creation: date
        as_update: updated
  - mermaid2
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Networking:
      - Overview: 01_networking/index.md
      - TCP: 01_networking/tcp.md
      - UDP: 01_networking/udp.md
  - Web:
      - Overview: 02_web/index.md
      - XSS: 02_web/xss.md
      - SQL Injection: 02_web/sql_injection.md
  - Windows:
      - Overview: 03_windows/index.md
      - PowerShell: 03_windows/powershell.md
      - Privilege Escalation: 03_windows/privilege_escalation.md

